apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  annotations :
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /sac
        pathType: Prefix
        backend:
          service:
            name: sac-svc
            port:
              number: 80
      - path: /importacion
        pathType: Prefix
        backend:
          service:
            name: importacion-svc
            port:
              number: 80
